### ISSUE TITLE
Need a Charles Session / .har file?

### ISSUE THREAD

**Issue by Meandmybadself** [nblavoie/wyzecam-api#1]
I've got a Charles Session file detailing all API interactions up until the point of retrieving a camera feed if that'd be helpful?

**Comment by Meandmybadself** [comment]
I was overcautious in redacting information.  Still not sure what is sensitive information & wanted to err on the side of being safe when it comes to cameras in my house.  Can provide any details over email.

[Wyzecam.chlsj.zip](https://github.com/nblavoie/wyzecam-api/files/1976370/Wyzecam.chlsj.zip)

**Comment by nblavoie** [comment]
Good, I'll had it to the project.
